import {useEffect} from "react"
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { motion } from "framer-motion"
import { opacity } from "../globalSetups/framer"
import useTranslation from 'next-translate/useTranslation'
import { useRouter } from 'next/router'
import styles from "../styles/pages/Home.module.css"

export default function Home() {

  let  { t }= useTranslation()
  const router=useRouter()

  useEffect(()=>{
    document.querySelector("body").style.fontFamily=router.locale==="hn"?"Noto Sans Devanagari":"Noto Sans Display";
  })

  return (
    <>
      <Head>
        <title>{t('common:title')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid place-items-center">
         <div className="grid place-items-center" style={{width: "100%",height: "calc(100vh - 10rem)",position: "relative"}}>
           <Image
             layout="fill"
             src="/static/hero.jpg"
             alt="Heading"
             objectFit="cover"
             priority={true}
            />
            <motion.div
              initial="initial"
              exit="initial"
              animate="final"
              variants={opacity}
              className="absolute top-auto left-1/4 -translate-x-100 p-5 rounded" 
              style={{background:"rgba(245,158,11,0.7)",transform:"translateX(-100%)"}}>
              <h1 className="text-white text-2xl font-semibold">THE NEW <br/> AYODHYA</h1>
              <p className="text-white text-xs mt-2">PEERLESS REFINEMENT AND LUXURY</p>
              <button 
                className="mt-2 basicButton"
                onClick={()=>router.push("/gallery")}
              >VIEW GALLERY </button>
            </motion.div>
           {/* <p>{t('common:home.body')}</p> */}
         </div>
      </div>
      <div className="grid" style={{gridTemplateColumns:"0.4fr 0.8fr"}}>
        <div className={`${styles.aug5Text} grid place-items-center `}>
            <div className="w-2/4">
                  <p className="text-center leading-8">On August 5 of 2022, Prime Minister Narendra Modi attended Ram Mandir&apos;s bhoomi pujan in Ayodhya.</p>
            </div>
        </div>
        <div className="grid items-center">
          <div className={`${styles.aug5container}`}>
            <p className={`${styles.overlayingText} text-amber-500 font-semibold text-9xl`}>5<sup>th</sup> August</p>
            <p className={`${styles.baseText} GFG  uppercase font-semibold`}>ayodhya</p>
          </div>
        </div>
      </div>
    </>
  )
}


