import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/global/Navbar'
import styles from '../styles/Home.module.css'
import useTranslation from 'next-translate/useTranslation'
import { useRouter } from 'next/router'
import Link from 'next/link'

export default function Home() {

  let  { t }= useTranslation()
  const router=useRouter()
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <h1 className="m-10 bg-gray-500">aman pratap singh</h1>
      <h1>ayodhya</h1>
      <h1>{t('common:greeting')}</h1>
      <ul>
        {router.locales.map(locale=>{
          return(
            <li key={locale}>
              <Link href={router.asPath} locale={locale}>
                <a>{locale}</a>
              </Link>
            </li>
          )
        })}
      </ul>
    </>
  )
}
